import random
import numpy as np
import torch

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 64

# --- RUNTIME MODE PARAMETER ---
# Options: "CONTROL", "DAGGER", "LYAPUNOV_DAGGER", "LYAPUNOV_DAGGER_TWO_STEP", "LYAPUNOV_ONLY", "TWO_STEP_ONLY"
TRAINING_MODE = None

# Trajectory Settings
NUM_TRAIN_TRAJECTORIES = 160
NUM_VAL_TRAJECTORIES = 40
TRAJECTORY_LENGTH = 1000

# DAgger Settings
DAGGER_ITERATION_COUNT = 5
DAGGER_ITERATIONS = DAGGER_ITERATION_COUNT if TRAINING_MODE in ["DAGGER", "LYAPUNOV_DAGGER", "LYAPUNOV_DAGGER_TWO_STEP"] else 1
DAGGER_ROLLOUTS = 20
DAGGER_STEPS = 1000
EXACT_LENGTH = False

DAGGER_EPOCHS = 20
BC_TRAIN_EPOCHS = DAGGER_EPOCHS if TRAINING_MODE in ["DAGGER", "LYAPUNOV_DAGGER", "LYAPUNOV_DAGGER_TWO_STEP"] else DAGGER_EPOCHS*DAGGER_ITERATION_COUNT
CRITIC_PRETRAIN_EPOCHS = 20

# Data Dimension & Constraints
KNN_SUBSAMPLE_SIZE = 5
ACTION_MIN = -2.0
ACTION_MAX = 2.0

# Batch Sizes
POLICY_BATCH_SIZE = 64  # Accessible via config.BATCH_SIZE
CRITIC_BATCH_SIZE = 256

# Optimization Learning Rates
POLICY_LR = 1e-3
POLICY_WD = 1e-5

CRITIC_LR = 1e-3
CRITIC_WD = 1e-4
CRITIC_GRAD_CLIP = 1.0
CRITIC_NOISE_SCALE = 0.3

LYAPUNOV_LR = 1e-3
LYAPUNOV_WD = 1e-5

# Loss Multipliers & Algorithmic Weights
TWO_STEP_LOSS_WEIGHT = 1.0
LYAPUNOV_LOSS_WEIGHT = 0.5
LYAPUNOV_ALPHA_DECAY = 0.01

# Evaluation Environments
MID_TRAIN_EVAL_EPISODES = 3
FINAL_EVAL_EPISODES = 10
DAGGER_ROLLOUT_EPISODES = 5

SEED = 42

def set_seed():
    torch.manual_seed(SEED)
    np.random.seed(SEED)
    random.seed(SEED)